from .VelocityBallToGoalReward import VelocityBallToGoalReward
from .AlignBallGoal import AlignBallGoal
from .InAirReward import InAirReward
from .SpeedTowardBallReward import SpeedTowardBallReward
from .AirTouchReward import AirTouchReward
from .BallTouchReward import BallTouchReward
from .FaceBallReward import FaceBallReward
from .LandingRecoveryReward import LandingRecoveryReward
from .SpeedReward import SpeedReward
from .AerialNavigation import AerialNavigation
from .BoostReward import BoostReward
from .BoostPickupReward import BoostPickupReward
from .GoalSpeedBonusReward import GoalSpeedBonusReward
from .AlignmentReward import AlignmentReward
from .BoostLoseReward import BoostLoseReward
from .FlipResetReward import FlipResetReward
from .FlipResetRewardOPTI import FlipResetRewardOPTI
from .FlipResetHelperRewardOPTI import FlipResetHelperRewardOPTI
from .AerialDistanceReward import AerialDistanceReward
from .WavedashReward import WavedashReward
from .AdvancedTouchReward import AdvancedTouchReward
from .BallTravelReward import BallTravelReward
from .ExampleReward import ExampleReward
